### PR TITLE
Web API 0.1.0 - Refactor for better semantics and correct constraints

### PR DESCRIPTION
**Pull request by AsherJingkongChen**
# Web API 0.1.0 - Refactor for better semantics and correct constraints

## Summary

A breaking change to Web API

## Description

> Click [here](https://editor.swagger.io/?url=https://raw.githubusercontent.com/Basketball-Competition-Dashboard/doc/web-api-0.1.0/api/web/openapi.yml) to preview using Swagger Editor v4!

This PR refactors the CRUD operations for the `player`, `team`, and `game` entities in the Web API to improve semantics and ensure correct constraints are applied. The changes include the creation of new endpoints for each entity, the introduction of dedicated schemas, and rewrite constraints particularly for the `player` entity.

## Motivation or Context

This change is required to address improper designs previously and improve the overall structure and clarity of the API. By refactoring these operations, I aim to provide a more intuitive and maintainable specification. Additionally, this refactor helps ensure that the API adheres to best practices and correct constraints.

## Checklist

| Item          | Is checked? | Description                                        |
| ------------- | ----------- | -------------------------------------------------- |
| Explanation   | O           | My changes are well-explained.                     |
| Documentation | O           | My works are well-commented or clear.              |

### CODE REVIEW

**Comment by AsherJingkongChen** [comment]
## Screenshot

This was taken from my browser at https://editor.swagger.io/?url=https://raw.githubusercontent.com/Basketball-Competition-Dashboard/doc/web-api-0.1.0/api/web/openapi.yml

image

**Comment by AsherJingkongChen** [comment]
## Note

Sorry, most Web API endpoints are affected. You may need to rewrite implementations and stubs.

**Comment by yuching29** [comment]
player-stats:
1. 針對更新(patch)：範例request是
{
  "hit": 1,
  "free_throw": 4,
  "score": 30
}
那這樣例如沒回傳的assist, rebound, etc.是回傳None還是維持原本的值？

**Comment by AsherJingkongChen** [comment]
@michelle871207 

> player-stats:
> 1. 針對更新(patch)：範例request是
> {
>   "hit": 1,
>   "free_throw": 4,
>   "score": 30
> }
> 那這樣例如沒回傳的assist, rebound, etc.是回傳None還是維持原本的值？

PATCH 的語義是部分替換，有出現的欄位才會做替換。

假設 request body 如下：

```json
{
   "hit": null,
   "free_throw": 4,
   "score": 30
}
```

需要更新的欄位即 `hit`, `free_throw`, `score`。

這三個欄位都是 non-required，所以沒出現就是沒影響，不會報錯。

這點稍後會補充在 spec descriptions。

**Comment by AsherJingkongChen** [comment]
```diff
+ PATCH /games/{id}/teams/{team_id}
```

**Comment by AsherJingkongChen** [comment]
## New feature (fix)

To fix lack of constraint,
I've added `PATCH /games/{id}/teams/{team_id}` where `team_id` corresponds to `Database.Attend.TID`.

**Comment by AsherJingkongChen** [comment]
# Contributor Added

@michelle871207

**Comment by AsherJingkongChen** [comment]
Screenshot

This was taken from my browser at https://editor.swagger.io/?url=https://raw.githubusercontent.com/Basketball-Competition-Dashboard/doc/web-api-0.1.0/api/web/openapi.yml

image

**Comment by AsherJingkongChen** [comment]
## Screenshot

These were taken from my browser at https://editor.swagger.io/?url=https://raw.githubusercontent.com/Basketball-Competition-Dashboard/doc/web-api-0.1.0/api/web/openapi.yml

image

image

**Pull request merged**
